FROM python:3.10.4

COPY ../app /app
COPY requirements_web.txt /app
WORKDIR /app

RUN pip install --default-timeout=100 -r requirements_web.txt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]